services:

  mongo:
    image: mongo:8.0.13
    restart: always
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGO_PORTS:-27017}:27017

  bff-demo:
    image: andrewthomaslee/bf-demo:p9n6bvpdf2r1ghz7k9myk8bdkfws58db
    restart: always
    depends_on:
      - mongo
    environment:
      - DB_URI=${DB_URI:-mongodb://mongo}
      - SECRET_KEY=${SECRET_KEY:-should-be-changed}
      - FAKE_DATA=${FAKE_DATA:-True}
    networks:
      - backend
    tty: true
    stdin_open: true
    ports:
      - ${PORTS:-7999}:7999

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge