[project]
name = "monotes"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "andrewthomaslee", email = "andrewthomaslee.business@gmail.com" },
]
requires-python = ">=3.13"
dependencies = [
    "datastar-py>=0.6.5",
    "fastapi>=0.116.1",
    "jinja2>=3.1.6",
    "marimo>=0.15.0",
    "mohtml>=0.1.11",
    "uvicorn>=0.35.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "marimo[recommended]>=0.15.0",
    "pydantic-settings>=2.10.1",
    "pyrefly>=0.29.2",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "python-lsp-server>=1.13.0",
    "ruff>=0.12.8",
    "watchdog>=6.0.0",
    "websockets>=15.0.1",
]
