apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.prod.yml convert -o manifest/ -n bff-demo --pvc-request-size 2G
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: bff-demo
  name: bff-demo
  namespace: bff-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bff-demo
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.prod.yml convert -o manifest/ -n bff-demo --pvc-request-size 2G
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: bff-demo
    spec:
      containers:
        - env:
            - name: DB_URI
              value: mongodb://mongo
            - name: FAKE_DATA
              value: "True"
            - name: SECRET_KEY
              value: should-be-changed
          image: andrewthomaslee/bf-demo:latest
          name: bff-demo
          ports:
            - containerPort: 7999
              protocol: TCP
          stdin: true
          tty: true
      restartPolicy: Always
