apiVersion: apps/v1
kind: Deployment
metadata:
  name: bf-demo-deployment
  labels:
    app: bf-demo
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: bf-demo
  template:
    metadata:
      labels:
        app: bf-demo
    spec:
      containers:
      - name: bf-demo
        image: andrewthomaslee/bf-demo:latest